### ISSUE TITLE
Can't select wallet backup file in "open file" dialog

### ISSUE THREAD

**Issue by ghost** [Multibit-Legacy/multibit-hd#219]
![multibithd](https://cloud.githubusercontent.com/assets/8447873/4690805/c9e242de-56fa-11e4-84d8-e74ea1cd8a5c.png)
Hello, it just happened that I did not remember the wallet password.
1. I was missing a message "Wrong password!". It just goes read.
2. So I tried "restore password from seed". Problem is, I had a seed and password for PB3 , and a seed and password (which I did not remember) for the current dev code. Password for PB3 did not work so I put in the seed for PB3, that showed "verified", but then the message "No password could be recovered for that seed phrase". Mysterious.
3. So I tried "Restore wallet". Again seed is verified, but in the open wallet backup file dialog, I am not able to select a file, see screenshot. But in that directory there are the backup files, named like mbhd-24727537-8652bdd8-b9658c65-013e0213-f04ab437-20140830110017.zip.aes with proper permission for the running user.
4. I was confused, what seed phrase to use, so I tried the seed phrase for the current dev code. Also that seed phrase showed "verified", but also "No password could be recovered for that seed phrase". How can two seed phrases be verified for one wallet??? What does that mean "verified"? I changed one word, then the seed was not verified anymore.
5. I tried some passwords and finally I had luck and had the right password to open the wallet.
6. -> Bad user experience when forgetting password!

**Comment by romeza** [comment]
Hello dear ... I'm a rookie. I have a problem with my wallet multi-bit hd. A pleasure to greet. I wanted to make a query. I have a problem with HD Multibit wallet.
Perform a reinstallation because the PC format. NO my balance appears.
I will Blockchain and there if it appears, but the wallet multi-bit HD not appear. I change bitcoin address during installation. weird thing happened to me. I kept backup in PC. I can see many mbhd-XXXXXXXXXXXXXXXXXXXXXXXXXXXXXX.zip.aes files, I also have wallet words but when I try to restore old wallet after fresh install on new pc, I enter the words and select backup filder, it says that no backup files were found.

But they are there, present.

So I clicked on ok, window disappeared and new wallet opened. I entered my password (the one I used with old backuped wallet), it got accepted and bitcoin started to sync.

But when it finished, it showed 0 BTC. And moreover, I found nowhere again the option, to restore from cloud backup .zip.aes files.

What happened here? How to restore bitcoins using wallet words and online backup?

Please your help how to fix it.
My email: negociosporweb@hotmail.com

From now Thanks

**Comment by jim618** [comment]
Duplicate of stackexchange query:
http://bitcoin.stackexchange.com/questions/43195/restore-portfolio-multibit

Please don't post the same query over and over

**Comment by romeza** [comment]
Thanks Jim .... achieves fix with your instructions. Very thankful!.

**Comment by romeza** [comment]
Thanks Jim .... achieves fix with your instructions. Very thankful!.
