### ISSUE TITLE
Many unconfirmed transactions

### ISSUE THREAD

**Issue by Fires04** [Multibit-Legacy/multibit-hd#958]
Hi, I got problem with multibit. I got many and many unconfirmed transaction. I try 

1) reinstall multibit
2) recover wallet
3) repair wallet .. still nothing :(  what could be problem ? 
4) using latest version of Multibit HD
Screenshot here:

https://i.imgsafe.org/ee8c8682ff.png
https://i.imgsafe.org/ee8c9e3b47.png

**Comment by vanboohen** [comment]
By recover you mean restore wallet from wallet words?

**Comment by Fires04** [comment]
yes .

2017-02-04 17:02 GMT+01:00 vanboohen <notifications@github.com>:

**Comment by vanboohen** [comment]
I had the same problem for a 6 months or so. I think it's a combination of 2 or more bugs(usually repair is enough/restore must help) Do you still have wallet and its password

**Comment by Fires04** [comment]
yes .. I try intall clean wallet ( remove Multibit config folder ) and
setup whole wallet from wallet words ..  It make whole new sync .. but
again unconffirmed transactions :( and there is no way how to get private
key from Multibit HD for export it to another wallet.

2017-02-04 18:17 GMT+01:00 vanboohen <notifications@github.com>:

**Comment by vanboohen** [comment]
Contac me vanboohen(yoknowwhat)mail.ru. I will guide you through this :)

**Comment by Fires04** [comment]
Hi - SOLVED

I try, remove all files , instal old version 0.1.4 , recover from wallet words and voila all transactions are confirmed.

**Comment by vanboohen** [comment]
Sorry I was in the hospital. Good for you

**Comment by jhaand** [comment]
I have the same problem at this moment. 
This is a major bummer at this moment and causing me a lot of headaches this weekend.

Currently trying the Multibit-HD 0.1.1 route. 
Another method I read for getting at your Bitcoins is using Breadwallet. But then everything is on a mobile device for a short while.

**Comment by jhaand** [comment]
The Multibit-HD 0.1.1 route works. 
You don't even have to wipe your old wallet. Just do a repair. 

I hope for Multibit-HD and Keepkey that they get this sorted out. 
But I'm outta here.

**Comment by Ringovich** [comment]
Hi everybody, I am having a similar problem and I'm very new to this. 

To tell it from the beginning, I was to order bitcoins and had not used my wallet for a few weeks. When i logged in, all my older transactions were unconfirmed strangely enough. I thought it was just some sort of lag, so I didn't bother with it at first. Also, the tiny amound I had left in my wallet from earlier was also listed as unconfirmed at the top.

I made an order for bitcoins anyway that did arrive, but the older transactions still didn't change from unconfirmed. So I now had my newly ordered bitcoins, but my old balance were still on the side as unconfirmed.

Now I tried to send the bitcoins I had just recieved onwards, but It has been stuck on sending, being unconfirmed, since then. That was two days ago. So I tried repairing, and the old transactions resolved to their proper status, but the new send is still unconfirmed. Also the tiny amount I mentioned that I had since earlier, is now in my balance. However, the tiny amount left over from this recent send, that up until the repair was in my balance, is now unconfirmed. So the earlier tiny amount switched place with the new tiny amount. 

So now I have 0,35 dollars balance and 0,11 in unconfirmed, while my send is going nowhere.
I have tried repairing several times more and have been giving it time to send but nothing, and I am scared of losing my money.

Will that 0.1.1 route do anything for my problem? If so, how do I go about it? Any other things to try?
If you need screenshots or additional info I will post on request.

Hope you can help and thanks in advance

**Comment by vanboohen** [comment]
Have you tried restorimng your wallet from wallet words ?

**Comment by Kaggelpiep** [comment]
How does your transaction show up on blockchain.info? I had a few transactions that literally took several days to be confirmed although all fees were sufficient and it had to do with the max 1Mb block chain size. Just wait.

**Comment by Fires04** [comment]
If somebody have same issue. Download really old version od multibit .. restore wallet .. Finish.
