### ISSUE TITLE
MULTIBIT STEAL MY BITCOINS ?!

### ISSUE THREAD

**Issue by ghost** [Multibit-Legacy/multibit-hd#990]
Yesterday I created an account in the MultiBit app and did a transfer, soon after the problem of the password that spoke that was wrong.
I followed the steps to pick up the private purse and import my wallet. When I minded I had a history transfer for 2 addresses:

144V8jxtmMFdx9rf3hxjx9vW2Xane4XKYV
1FGy6Sn15xtxa5hQkro9W31Y3T3YLXp

There was nothing left in the wallet, my password was impossible to steal because I had just created the account and saved it nowhere.

My bitcoins were stolen.

Sorry for english, I'm not american.

**Comment by cashoncommand** [comment]
I agree with you..  I have 3 wallets, and the 1 wallet that had bitcoins seems to have been locked and I cannot login and they have STOLEN the bitcoins.

**Comment by ghost** [comment]
Yeah, i never use this wallet again...

**Comment by cashoncommand** [comment]
HI..  I received this message from another member..
"I found a solution. You download this wallet through an Android or IOS device https://breadwallet.com/.
Then you do not create a wallet, but you do a restoration and insert the seed of your MultibitHd wallet, and then just send the money to another wallet. I hope it helped you.?

I just tested it and it worked..

When you send the bitcoins to another wallet.  It may come back with "insufficient funds".  When it gives you an amount to adjust.  You need to select the amount and then it will work.  Don't manually enter the amount, because it doesn't recognise it properly.  
BUT IT WORKS WHEN YOU SELECT THE SUGGESTED AMOUNT..  :)

GOOD LUCK

**Comment by bgok** [comment]
Your coins were not stolen. The software has an unfortunate bug.

As @cashoncommand suggested, importing you 'wallet words' into [breadwallet](https://breadwallet.com/) will allow you to see your balance and send transactions.

**Comment by ghost** [comment]
I imported my wallet from MultibitHD into the blockchain, but the problem is that the money did not come and the transaction history is saying that it was sent to the following addresses:
144V8jxtmMFdx9rf3hxjx9vW2Xane4XKYV
  (0.020434 BTC)
1FGy6Sn15xtxa5hQkro9W31Y3T3YLXpns9
  (0.004076 BTC)

I did not perform this transfer, it occurred in the period in which my account was bugged.

**Comment by cashoncommand** [comment]
Logan,

Try the Suggestion that I put up..  It worked for me and I got my Bitcoins.
